name: unimate
description: >-
  UniMate - a cross-platform student study and life planner built with Flutter
  for ICT725 User Experience and Mobile Application Development (Assessment 4).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  fl_chart: ^0.68.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
